### ISSUE TITLE
Ethernet SD card demo  - esp_eth_driver_install_failed (PlatformIO)

### ISSUE THREAD

**Issue by DO7LZ** [OLIMEX/ESP32-POE2#1]
Hi,

I tried to get the [Simple Ethernet and SD card demo for Arduino](https://raw.githubusercontent.com/OLIMEX/ESP32-POE/master/SOFTWARE/ARDUINO/ESP32_PoE_Ethernet_SD_Card_Arduino/ESP32_PoE_Ethernet_SD_Card_Arduino.ino) example working with PlatformIO. But there seems to be an error with the Ethernet libary.

```
rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
Card Mounted
E (664) lan87xx: lan87xx_pwrctl(409): power up timeout
E (665) lan87xx: lan87xx_init(491): power control failed
E (665) esp_eth: esp_eth_driver_install(215): init phy failed
[   674][E][ETH.cpp:324] begin(): esp_eth_driver_install failed
```

What I did:

1. Create a new PlatformIO project with board **OLIMEX ESP32-PoE** and Framework Arduino. (platformio/espressif32 v6.6.0)
2. Pasted in the above mentioned example into `main.cpp` and added `monitor_speed = 115200` to `platformio.ini`
3. Inserted SD card and plugged in network and USB to board.
4. Build and upload. Followed by the console output above.

Can anyone give me a little push?

**Comment by JulesThuillier** [comment]
Hi !

Same issue here.

**Comment by JulesThuillier** [comment]
@DO7LZ have you found a solution ?

**Comment by DanKoloff** [comment]
Regular ESP32-POE config is not suitable for ESP32-POE2. If there is ESP32-POE-WROVER or ESP32-POE-ISO-WROVER config it would be suitable. 

ESP32-POE2 uses ESP32-WROVER module that uses GPIO16 and GPIO17 for the internal PSRAM, so you need to define GPIO0 for the Ethernet clock (instead of GPIO17). Else the Ethernet won't work.

And if you need to use GPIO16 (usually used for I2C) change it with GPIO33.

**Comment by jonathanelmgren** [comment]
In the latest firmwares of Micropython you should use `ref_clk` and `ref_clk_mode` to set the clock mode for `network.LAN`.

I got it working with this code:

```
import network
import machine
import time


def initialize_ethernet():
    # Configure the PHY power pin as a machine.Pin object
    phy_power = machine.Pin(12, machine.Pin.OUT)
    phy_power.value(0)  # Start with PHY power off
    time.sleep(1)
    phy_power.value(1)  # Power up the PHY
    time.sleep(1)  # Wait for the PHY to power up

    # Define the MDC and MDIO pins as machine.Pin objects
    mdc_pin = machine.Pin(23)
    mdio_pin = machine.Pin(18)
    ref_clk_pin = machine.Pin(0)

    try:
        # Initialize the LAN interface with the correct PHY type and parameters
        lan = network.LAN(
            mdc=mdc_pin,  # MDC pin as machine.Pin
            mdio=mdio_pin,  # MDIO pin as machine.Pin
            power=phy_power,  # PHY power pin as machine.Pin
            phy_type=network.PHY_LAN8710,  # PHY type
            phy_addr=0,  # PHY address
            ref_clk=ref_clk_pin,  # Reference clock pin as machine.Pin
            ref_clk_mode=machine.Pin.OUT,  # Reference clock mode as output
        )
        lan.config(hostname="esp32-ethernet-client")
        lan.active(True)
        time.sleep(2)  # Allow the interface to stabilize

        while True:
            if lan.isconnected():
                print("Ethernet is supported and connected.")
                print("Network config:", lan.ifconfig())
            else:
                print(
                    "Ethernet is supported but not connected. Please connect an Ethernet cable."
                )
            time.sleep(5)
    except Exception as e:
        print("Error initializing Ethernet:", e)


# Run the initialization function
initialize_ethernet()
```

Working both with PoE and USB with regular Ethernet. Firmware used was https://micropython.org/download/ESP32_GENERIC/ and latest release from `Firmware (Support for SPIRAM / WROVER)` section

**Comment by DO7LZ** [comment]
My solution for the problem:

Create a new PlatformIO project with board Espressif **ESP-WROVER-KIT** instead of OLIMEX ESP32-PoE and Framework Arduino. 

Paste the example in `main.cpp` and add the following directly before `#include <ETH.h>`:

```
#ifndef ETH_PHY_TYPE
#define ETH_PHY_TYPE ETH_PHY_LAN8720
#define ETH_PHY_ADDR 0
#define ETH_PHY_MDC 23
#define ETH_PHY_MDIO 18
#define ETH_PHY_POWER 12
#define ETH_CLK_MODE ETH_CLOCK_GPIO0_OUT
#endif
```
 
This is also mentioned in the actual user manual.
With this the example seems to work. It's getting an IP address via DHCP and is able to send a GET request to google.com and prints out the response. On push of BUT1 the files are properly written to SD card. I don't have tested any other things yet.
